name: some name
run-name: ${{ github.actor }} is a cool dude
on: [ push ]
jobs:
  do-something-cool:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g bats
      - run: bats -v